services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:8.0
    environment:
      - MONGODB_INITDB_DATABASE=${MONGODB_DB:-pizzox}
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-root}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-admin}
    volumes:
      - mongodb_data:/data/db:rw
    ports:
      - "27017:27017"

  redis:
    image: redis:7.4
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data:rw
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data:
