controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    defaults:
        _locale: en

pizza:
    path: /pizzas
    controller: App\Controller\PizzaController::index
    defaults:
        _locale: en